In [44]:
# My details are as follows

In [45]:
data = {
    "Name": "Aritra Mondal",
    "Section": "A2",
    "Roll_no": "002311001091"
}

for key, value in data.items():
    print(f"{key}: {value}")

Name: Aritra Mondal
Section: A2
Roll_no: 002311001091


In [46]:
# Task 1 - Read data from a file that has been uploaded

In [47]:
file = open("/content/091_sample.txt","r")
print(file.read())

Today is the first AI Class and we have been assigned with a task to read and write contents of a file. Although we have been told to use any state-of-the-arts AI agent to write our code but we should understand each and every line of it.
This task have been assigned to everyone to familarise themselves with the google colab environment It is fun to work here but with a bitter taste of colab's slow functionality.


In [48]:
# Task 2 - Creating a new file and writing user input contents into it.

In [49]:
file = open("/content/091_sample_write.txt","w")

In [50]:
content = input("Enter the content you want to write in the file: ")

Enter the content you want to write in the file: CNN is undergoing significant changes as part of its strategy to adapt to the evolving media landscape. The network announced plans to cut approximately 100 jobs, representing about 3% of its workforce. These layoffs are part of a broader effort to consolidate its television and digital news divisions into a single unit, aiming to enhance operational efficiency and focus more on digital growth. CEO Mark Thompson emphasized the importance of building a robust digital business, citing ambitions to develop subscription-ready products offering news, analysis, and context in new formats. This move aligns with CNN's goal to reduce its reliance on traditional cable TV and expand its digital presence.


In [51]:
file.write(content)

702

In [52]:
file.seek(0)

0

In [53]:
# Reading the data of the file that has been written just now to analyse the contents

In [54]:
file = open("/content/091_sample_write.txt","r")
print(file.read())

CNN is undergoing significant changes as part of its strategy to adapt to the evolving media landscape. The network announced plans to cut approximately 100 jobs, representing about 3% of its workforce. These layoffs are part of a broader effort to consolidate its television and digital news divisions into a single unit, aiming to enhance operational efficiency and focus more on digital growth. CEO Mark Thompson emphasized the importance of building a robust digital business, citing ambitions to develop subscription-ready products offering news, analysis, and context in new formats. This move aligns with CNN's goal to reduce its reliance on traditional cable TV and expand its digital presence.


In [55]:
# Task 3 - Perform normal dfs operation and showing all the intermediate steps.

In [56]:
# Matrix DFS traversal with intermediate steps

# Direction vectors: left, down, right, up
dRow = [0, 1, 0, -1]
dCol = [-1, 0, 1, 0]

def is_valid(r, c, ROW, COL, visited):
    return (0 <= r < ROW and 0 <= c < COL and not visited[r][c])

def dfs_matrix(grid, start_r=0, start_c=0):
    ROW, COL = len(grid), len(grid[0])
    visited = [[False]*COL for _ in range(ROW)]
    stack = [(start_r, start_c)]

    while stack:
        r, c = stack.pop()

        if not is_valid(r, c, ROW, COL, visited):
            continue

        visited[r][c] = True
        print(f"Visiting cell ({r}, {c}) → {grid[r][c]}")

        # Push neighbors onto stack
        for i in range(4):
            nr, nc = r + dRow[i], c + dCol[i]
            if is_valid(nr, nc, ROW, COL, visited):
                stack.append((nr, nc))

# Example usage:
grid = [
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9]
]
dfs_matrix(grid)


Visiting cell (0, 0) → 1
Visiting cell (0, 1) → 2
Visiting cell (0, 2) → 3
Visiting cell (1, 2) → 6
Visiting cell (2, 2) → 9
Visiting cell (2, 1) → 8
Visiting cell (1, 1) → 5
Visiting cell (1, 0) → 4
Visiting cell (2, 0) → 7


In [57]:
# Task 4 - Read tha start and target matrix and give all the corresponding steps(states)

In [63]:
import numpy as np

def get_matrix_input(name):
    """Prompts the user to input a 3x3 matrix."""
    print(f"Enter the elements of the {name} matrix (9 integers):")
    matrix = []
    for i in range(3):
        row = list(map(int, input(f"Row {i + 1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

def is_valid_move(matrix, x, y):
    """Checks if the move is within the matrix bounds."""
    return 0 <= x < 3 and 0 <= y < 3

def iterative_dfs(start, target):
    """Performs iterative DFS to find the transformation path from start to target."""
    stack = [(start, [], set())]  # (current matrix, path, visited states)
    step = 0

    while stack:
        current, path, visited = stack.pop()
        visited.add(tuple(current.flatten()))

        print(f"Stack at Step {step}:")
        for state in stack:
            print(state[0])  # Print only the current matrix of each state
        print("-----")

        if np.array_equal(current, target):
            path.append((step, current.copy()))
            return path

        x, y = np.where(current == 0)
        x, y = x[0], y[0]  # Extract the row and column of the empty cell

        # Define possible moves: up, down, left, right
        moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        for dx, dy in moves:
            nx, ny = x + dx, y + dy
            if is_valid_move(current, nx, ny):
                new_matrix = current.copy()
                new_matrix[x, y], new_matrix[nx, ny] = new_matrix[nx, ny], new_matrix[x, y]
                if tuple(new_matrix.flatten()) not in visited:
                    stack.append((new_matrix, path + [(step, current.copy())], visited))
        step += 1

    return None

def main():
    """Main function to execute the matrix transformation."""
    start = get_matrix_input("start")
    target = get_matrix_input("target")

    path = iterative_dfs(start, target)
    if path:
        print("\nTransformation path:")
        for step, matrix in path:
            print(f"Step {step}:")
            print(matrix)
    else:
        print("No transformation path found.")

if __name__ == "__main__":
    main()


Enter the elements of the start matrix (9 integers):
Row 1: 1 2 3
Row 2: 4 5 6
Row 3: 7 8 0
Enter the elements of the target matrix (9 integers):
Row 1: 1 2 3
Row 2: 4 5 6
Row 3: 0 7 8
Stack at Step 0:
-----
Stack at Step 1:
[[1 2 3]
 [4 5 0]
 [7 8 6]]
-----
Stack at Step 2:
[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 0 6]
 [7 5 8]]
-----

Transformation path:
Step 0:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
Step 1:
[[1 2 3]
 [4 5 6]
 [7 0 8]]
Step 2:
[[1 2 3]
 [4 5 6]
 [0 7 8]]
